<?php

declare(strict_types=1);

use Symfony\Component\Routing\Loader\Configurator\RoutingConfigurator;

/**
 * Imported by the application:
 *
 *     # config/routes/iam.yaml
 *     iam:
 *         resource: '@DddIamBundle/config/routes.php'
 *
 * Only the plain controllers are here. The back-office CRUD routes are
 * generated by Sylius from the #[AsResource] metadata and loaded through
 * `sylius_resource_loader` — declaring them here too would register them twice.
 */
return static function (RoutingConfigurator $routes): void {
    $routes->import(
        dirname(__DIR__) . '/src/Infrastructure/Symfony/Controller/',
        'attribute',
    );
};
